# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [4]:
%run initialise.py

ModuleNotFoundError: No module named 'mdutils'

#### 1. Import the numpy package under the name `np` (★☆☆)

In [5]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [8]:
print(np.__version__)
print(np.__config__)

1.21.2
<module 'numpy.__config__' from 'C:\\Users\\ehern\\anaconda3\\envs\\DA_Env\\lib\\site-packages\\numpy\\__config__.py'>


#### 3. Create a null vector of size 10 (★☆☆)

In [10]:
zeros = np.zeros(10)
print(zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [13]:
zeros.itemsize

8

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [14]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [16]:
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [18]:
b = np.arange(10,50)
print(b)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [20]:
c = np.flip(b)
print(c)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [23]:
d = np.arange(0,9)
d = np.reshape(d, (3,3))
print(d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [25]:
e = np.array([1,2,0,0,4,0])
np.nonzero(e)

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [28]:
f = np.eye(3)
print(f)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [32]:
g = np.random.random((3,3,3))
print(g)

[[[0.96422244 0.42383986 0.79601418]
  [0.54478527 0.507927   0.21124467]
  [0.70332796 0.39307668 0.05983645]]

 [[0.21153205 0.46405675 0.53085263]
  [0.69399862 0.44691901 0.59725541]
  [0.13825057 0.36741812 0.35156312]]

 [[0.54170776 0.57344353 0.04548013]
  [0.42217992 0.42400108 0.11534733]
  [0.77465519 0.09521929 0.08211888]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [35]:
h = np.random.random((10,10))
print(h)

print(np.max(h))
print(np.min(h))

[[7.21497136e-01 5.19055706e-01 4.06658940e-01 7.37664141e-01
  1.90563931e-01 7.41038175e-01 3.62720738e-02 3.09917835e-01
  6.91619717e-01 1.82205588e-01]
 [1.04047745e-01 9.73615093e-01 7.58805358e-01 4.00458482e-01
  3.62358652e-01 2.03601049e-01 7.27891087e-04 9.75284213e-01
  3.55247788e-01 9.61758805e-01]
 [3.81258336e-01 8.41787136e-01 2.66675356e-01 3.90991989e-01
  6.26976129e-01 2.28435196e-01 1.96647761e-01 4.09578507e-01
  6.27277993e-01 1.52797275e-02]
 [8.35696686e-01 5.46035959e-01 5.57573212e-01 2.74766043e-01
  4.80445756e-01 5.74236028e-01 1.70591932e-01 5.61920046e-01
  1.91220917e-01 5.55498178e-01]
 [1.16533749e-01 8.78187163e-01 4.55895964e-01 7.75629870e-01
  6.65545696e-01 4.89077176e-01 1.42703416e-01 5.87422004e-01
  7.23803100e-01 7.83072644e-01]
 [9.92760647e-01 6.86915078e-01 4.67593310e-01 3.35299135e-01
  9.41270674e-01 7.36204079e-01 7.58253097e-01 9.76673638e-01
  6.51612674e-01 8.77115597e-01]
 [4.55374059e-01 7.06293722e-01 7.11926387e-01 2.65957822e

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [38]:
i = np.random.random(30)
print(i)

print(np.mean(i))


[0.66901712 0.34024289 0.01051617 0.30746863 0.81954686 0.41195031
 0.09791984 0.53893758 0.14670359 0.5816666  0.60729677 0.98856635
 0.76105058 0.07627453 0.10622294 0.41585921 0.06002285 0.61587515
 0.07196037 0.26601618 0.98472208 0.83465955 0.18628266 0.31176803
 0.08529891 0.12408443 0.14364551 0.65712825 0.25654354 0.4210588 ]
0.3966102096011742


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [43]:
j = np.ones((4,4))
print(j)

j[1:-1, 1:-1] = 0

print(j)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [53]:
k = np.ones((4,4))
print(k)

np.pad(k, (1,1), "constant", constant_values=(0, 0) )
print(k)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [63]:
x = np.arange(9).reshape((3,3))
np.diag(np.diag(x))


array([[0, 0, 0],
       [0, 4, 0],
       [0, 0, 8]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [83]:
m = np.ones((8,8))
print(m)

m_flatten = m.flatten()
print(m_flatten)

m_flatten[::2] = 0

print(m_flatten)


[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.
 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.
 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [84]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [86]:
a21 = np.tile(np.array([0,1]),(4,4))
print(a21)

[[0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [93]:
a22 = np.random.random((5,5))


a22_norm = (a22 - np.mean(a22)) / np.std(a22)


0.8470048105450825
1.8825188722257473


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [96]:
a24a = np.random.random((5,3))
a24b = np.random.random((3,2))

np.matmul(a24a, a24b)


array([[0.41323161, 0.42633965],
       [1.0365412 , 1.06849341],
       [0.86667035, 1.08927856],
       [1.53367968, 1.80599992],
       [1.2197893 , 1.42238149]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [111]:
a25 = np.arange(0,10)

a25[(a25 > 3) & (a25 < 8)] *= -1

print(a25)

[ 0  1  2  3 -4 -5 -6 -7  8  9]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [112]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**ZZ**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
# Z**ZZ**Z
# 2 << Z >> 2
# Z < - Z
# 1j*Z
# Z/1/1


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [125]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\ehern\AppData\Local\Temp/ipykernel_5040/3912170336.py:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
C:\Users\ehern\AppData\Local\Temp/ipykernel_5040/3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆)

In [132]:
a29 = np.random.uniform(-10,+10,10)
print(a29)

print(np.where(a29>0, np.ceil(a29), np.floor(a29)))

[-5.6006217   2.01372097  7.14302384  9.98659148 -6.27532652  3.24448049
 -9.82439064 -0.31873152  4.17096756  0.88375697]
[ -6.   3.   8.  10.  -7.   4. -10.  -1.   5.   1.]


#### 30. How to find common values between two arrays? (★☆☆)

In [141]:
a30a = np.arange(0,11)
a30b = np.arange(5,16)

np.intersect1d(a30a, a30b)

array([ 5,  6,  7,  8,  9, 10])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [142]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\ehern\AppData\Local\Temp/ipykernel_5040/244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [150]:
print(np.datetime64('today'))
print(np.datetime64('today') - 1)
print(np.datetime64('today') + 1)

2021-10-21
2021-10-20
2021-10-22


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [156]:
a34 = np.arange(np.datetime64("2016-07-01"), np.datetime64("2016-08-01"), dtype = "datetime64[D]")
print(a34)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [171]:
A = np.array([4.0, 4.0, 4.0])
B = np.array([6.0, 6.0, 6.0])

np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

print(A)


[-20. -20. -20.]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [185]:
a36 = np.random.uniform(0,10,10)

print(np.floor(a36))
print(np.trunc(a36))


[2. 6. 1. 6. 8. 7. 6. 5. 6. 4.]
[2. 6. 1. 6. 8. 7. 6. 5. 6. 4.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [175]:
a37 = np.tile(np.arange(0,5),(5,1))
print(a37)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [191]:
def generate():

    for x in range(10):

        yield x

a38 = np.fromiter(generate(), dtype = float, count = -1)

print(a38)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [193]:
a39 = np.linspace(0,1,11,endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [196]:
a40 = np.random.random(10)

a40 = np.sort(a40)

print(a40)

[0.1790336  0.22100755 0.28088127 0.42747769 0.54000677 0.62839859
 0.68178907 0.82060872 0.82186669 0.95776544]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [199]:
a41 = np.random.random(10)

np.add.reduce(a41)

5.342546056750422

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [204]:
a42a = np.random.random((3,3))
a42b = np.random.random((3,3))

np.array_equal(a42a, a42b)

False

#### 43. Make an array immutable (read-only) (★★☆)

In [207]:
a43  = np.arange(10)

a43.flags["WRITEABLE"] = False

a43[0] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [223]:
a44 = np.random.random((10,2))

print(a44)

a44b = a44

x = a44b[:,0]
y = a44b[:,1]

r = np.sqrt(x*x + y*y)
theta = np.arctan2(y, x)

a44b[:,0] = x
a44b[:,1] = theta

print(a44b)



[[0.39284011 0.25476902]
 [0.49486334 0.17959975]
 [0.56345853 0.92353549]
 [0.6735899  0.71452725]
 [0.32947398 0.03344882]
 [0.89930964 0.94549035]
 [0.68195787 0.84109615]
 [0.2665162  0.81186049]
 [0.98779756 0.83575127]
 [0.14595336 0.63491096]]
[[0.39284011 0.57534189]
 [0.49486334 0.34814519]
 [0.56345853 1.02297592]
 [0.6735899  0.8148809 ]
 [0.32947398 0.10117525]
 [0.89930964 0.81042585]
 [0.68195787 0.8895067 ]
 [0.2665162  1.25360216]
 [0.98779756 0.70221125]
 [0.14595336 1.34484187]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [226]:
a45 = np.random.random(10)

a45[a45 == np.max(a45)] = 0

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [232]:
Z = np.zeros((5,5), [('x',float),('y',float)])


print(Z["x"])
print(Z["y"])

Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)